version: "2"
services:
  service:
    image: weather-service:1.0
    network_mode: host
    entrypoint:
     - python3.6
     - main/service.py
  web:
    image: weather-service:1.0
    network_mode: host
    entrypoint:
     - python3.6
     - main/web.py
