version: "2"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home
    network_mode: host
    stop_signal: SIGTERM
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    entrypoint:
     - python3.5
     - main/service.py
  web:
    build:
      context: .
      dockerfile: Dockerfile
   volumes:
      - .:/home
    network_mode: host
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    entrypoint:
     - python3.5
     - main/web.py
