version: "2"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home
    network_mode: host
    stop_signal: SIGTERM
    entrypoint:
     - python3.6
     - main/service.py
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home
    network_mode: host
    entrypoint:
     - python3.6
     - main/web.py
